apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      name: apache
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: docker.io/jingom368/apache2_smboard:{{VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      # volumeMounts:
      # - name: tls-cert
      #   mountPath: /usr/local/apache2/conf/server.crt
      #   subPath: tls.crt
      # - name: tls-key
      #   mountPath: /usr/local/apache2/conf/server.key
      #   subPath: tls.key
      # volumes:
      # - name: tls-cert
      #   secret:
      #     secretName: my-tls-cert
      #     items:
      #     - key: tls.crt
      #       path: tls.crt
      # - name: tls-key
      #   secret:
      #     secretName: my-tls-cert
      #     items:
      #     - key: tls.key
      #       path: tls.key

---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: apache
  type: ClusterIP
